sensor:
  - platform: rest
    name: short_part_of_poem
    method: GET
    resource: https://v2.jinrishici.com/sentence
    headers:
      Content-Type: application/json
      X-User-Token: sFFKq2uhJIG1nYhfZuCUPgkSogRDCAPS
    value_template: '{{value_json["data"]["content"]}}'
    json_attributes_path: $.data
    json_attributes:
      - id
      - content
      - origin
      - warning
    scan_interval: 3600

homeassistant:
  customize:
    sensor.short_part_of_poem:
      friendly_name: 每日诗词
      icon: mdi:book
